version: "2"
services:
  mcrouter:
    image: turbulent/mcrouter
    depends_on:
      - cache
    ports:
      - 5000:5000
    command: >
      mcrouter --config-str='{"pools":{"A":{"servers":["cache:11211"]}},"route":"PoolRoute|A"}' -p 5000
  cache:
    image: memcached:alpine
    ports:
      - 11211
